const typeScale = require("./design-system/tailwind-plugins/build-type-scale");
const themeConfig = require("./design-system/design-tokens/tailwind-design");
// const { fontSize, fontFamily } = theme;

module.exports = {
  theme: {
    // If you want to override default tailwind values with your own set of values, then put them here

    extend: {
      // Here you can extend values generated by default.
      ...themeConfig,
      stroke: (theme) => theme("colors"),
      fill: {
        transparent: "transparent",
        none: "none",
      },
    },
  },
  variants: {},
  plugins: [typeScale],
};
